### PR TITLE
Fix issue #387 not to show alert when the user enrolls in a course

### LINKED ISSUE #387: Don't show alert when the user enrolls in a course
**Affected Component:**
Course Detail Page

**Expected Behavior:**
When the users taps the 'enroll' button, don't show an alert aksing if the user is sure about this.

**Actual Behavior:**
An alert asks if the users is realls sure about the enrollment.

**Additional Notes:**
To be consistent with the Android app.

### PR DESCRIPTION
**Pull request by maxxx777**
Fixes #387 

### Proposed Changes:
Create course enrollment without show an alert asking if the user is sure about this.

### CODE REVIEW

**Comment by jprberlin** [comment]
Thanks for your contribution. Lgtm. @mathebox can you also review and merge?

File: xikolo-ios/ViewControllers/Courses/CourseDetailViewController.swift [hunk 1]
```diff
@@ -83,28 +83,14 @@ class CourseDetailViewController: UIViewController {
...
-        let enrollAction = UIAlertAction(title: enrollActionTitle, style: .default) { _ in
-            EnrollmentHelper.createEnrollment(for: self.course).flatMap {
-                CourseHelper.refreshCourses()
+    func createEnrollment() {
+        EnrollmentHelper.createEnrollment(for: self.course).flatMap {
+            CourseHelper.refreshCourses()
             }.onSuccess { _ in
                 if let parent = self.parent as? CourseDecisionViewController {
                     parent.decideContent()
                 }
```
Comment (mathebox) [inline xikolo-ios/ViewControllers/Courses/CourseDetailViewController.swift]: The code in lines 89-92 have to much indentation. Please fix this, then it's good to be merged.
