### PR TITLE
Fix issue #269 to show indicator during login process

### LINKED ISSUE #269: Show indicator during login process
When pressing the login button, a activity indicator should appear to indicate running network request. Therefore [this](https://github.com/MasterCarl/SimpleRoundedButton) could be utilized.

### PR DESCRIPTION
**Pull request by maxxx777**
Fixes #269 

### Proposed Changes:
added 'SimpleRoundedButton' pod to use animation of SimpleRoundedButton for login button.

### CODE REVIEW

File: Podfile [hunk 1]
```diff
@@ -23,6 +23,7 @@ def ios_pods
     pod 'Hero', :git => 'https://github.com/lkzhao/Hero', :commit => 'd961f16'
     pod 'Shimmer', '1.0.2'
     pod 'ReachabilitySwift', '3'
+    pod 'SimpleRoundedButton'
```
Comment (mathebox) [inline Podfile]: Please add the version. Use `~>`.

File: xikolo-ios/ViewControllers/Main/LoginViewController.swift [hunk 2]
```diff
@@ -9,10 +9,11 @@
 import UIKit
 import WebKit
 import SafariServices
+import SimpleRoundedButton
 
 class LoginViewController : AbstractLoginViewController, WKUIDelegate {
-
-    @IBOutlet weak var loginButton: UIButton!
+
```
Comment (mathebox) [inline xikolo-ios/ViewControllers/Main/LoginViewController.swift]: Please remove this whitespace.
