### PR TITLE
Adjust status and navigation bar to course visual

### LINKED ISSUE #662: Adjust statusbar style and text color of navigation bar to course visual
**Describe the bug**
Since course visual are user-defined, we can't use a fixed text color for the navigation bar (not the brand color - the one when the course visual is shown) nor a fixed status bar style.

**To Reproduce**
1. Open a course with a light course visual

**Expected behavior**
Adjust the color according to the course visual. Use two color (white and black) since the status bar style is restricted to these two styles.

To determine to the text color:
1. Create a sub image for the area under the navigation bar https://stackoverflow.com/questions/4475881/return-a-subimage-from-a-uiimage
2. Calculate the average color of the sub image https://www.hackingwithswift.com/example-code/media/how-to-read-the-average-color-of-a-uiimage-using-ciareaaverage
3. Decide for black or white https://stackoverflow.com/a/2509596/7414898

We use SDWebImage to load the course visuals. So at first, the image can only be a colored area. We could observe images like [this](https://stackoverflow.com/a/31755686/7414898).

Optional: Add glow (as a background image) to increase to visibility.

**Screenshots**
Untitled

**Affected Component**
CourseViewController, CourseNavigationController

**Additional context**
When the header is hidden, the colors should obviously switch to black.

### PR DESCRIPTION
**Pull request by mathebox**
Fixes #662

### CODE REVIEW

File: iOS/ViewControllers/Courses/CourseViewController.swift [hunk 1]
```diff
@@ -135,7 +135,43 @@ class CourseViewController: UIViewController {
         guard self.isViewLoaded else { return }
         self.navigationItem.title = self.course.title
         self.titleLabel.text = self.course.title
-        self.headerImageView.sd_setImage(with: self.course.imageURL)
+        self.headerImageView.sd_setImage(with: self.course.imageURL) { [weak self] (image, _, _, _) in
```
Comment (CodeQualityBot) [inline iOS/ViewControllers/Courses/CourseViewController.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/openHPI/xikolo-ios/blob/229daa952cdd6cb1bd9f725ad02b6fdcbf9374a7/iOS/ViewControllers/Courses/CourseViewController.swift#L138"></span>Parentheses are not needed when declaring closure arguments.<br />
<code>unneeded_parentheses_in_closure_argument</code> <code>CourseViewController.swift:138</code></td>
    </tr>
  </tbody>
</table>

File: iOS/ViewControllers/Courses/CourseViewController.swift [hunk 2]
```diff
@@ -135,7 +135,43 @@ class CourseViewController: UIViewController {
...
+            self?.courseNavigationController?.adjustToUnderlyingColor(headerColor)
+        }
+    }
+
+    private func averageColorUnderStatusBar(withCourseVisual image: UIImage?) -> UIColor? {
+        guard let croppedImage = self.croppedImageUnderNavigationBar(withCourseVisual: image) else { return nil }
+
+        // copied from https://www.hackingwithswift.com/example-code/media/how-to-read-the-average-color-of-a-uiimage-using-ciareaaverage
+        let inputImage = CIImage(cgImage: croppedImage)
+        let extentVector = CIVector(x: inputImage.extent.origin.x, y: inputImage.extent.origin.y, z: inputImage.extent.size.width, w: inputImage.extent.size.height)
```
Comment (CodeQualityBot) [inline iOS/ViewControllers/Courses/CourseViewController.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/openHPI/xikolo-ios/blob/229daa952cdd6cb1bd9f725ad02b6fdcbf9374a7/iOS/ViewControllers/Courses/CourseViewController.swift#L149"></span>Line should be 160 characters or less: currently 164 characters<br />
<code>line_length</code> <code>CourseViewController.swift:149</code></td>
    </tr>
  </tbody>
</table>

File: iOS/ViewControllers/Courses/CourseViewController.swift [hunk 3]
```diff
@@ -135,7 +144,47 @@ class CourseViewController: UIViewController {
...
+        let topInset: CGFloat
+        if #available(iOS 11, *) {
+            topInset = self.view.safeAreaInsets.top
+        } else {
+            topInset = self.view.layoutMargins.top
+        }
+
+        let imageScale = image.size.width / self.view.bounds.width
+        let transform = CGAffineTransform(scaleX: imageScale, y: imageScale)
+        let y = (image.size.height - self.headerImageView.bounds.height * imageScale) / 2 / imageScale
```
Comment (CodeQualityBot) [inline iOS/ViewControllers/Courses/CourseViewController.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/openHPI/xikolo-ios/blob/d81b4223580bc4f209f709f6499724ab36bc67b0/iOS/ViewControllers/Courses/CourseViewController.swift#L185"></span>Variable name should be between 3 and 40 characters long: ‘y’<br />
<code>identifier_name</code> <code>CourseViewController.swift:185</code></td>
    </tr>
  </tbody>
</table>
