### PR TITLE
Fix position label of a course item in navigation bar

### LINKED ISSUE #730: Progress label in CourseItemViewController shows incorrect numbers
**Describe the bug**
At the moment, the progress label in the CourseItemViewController shows wrong positions and a wrong total amount of course items, as hidden items are taken into account as well.

**To Reproduce**
1. Go to a course you are enrolled in (f.i. the imdb course)
2. Select the last course item

**Expected behavior**
The number of actual items should be shown as well as the actual position of the currently visited item.

**Screenshots**

**Affected Component**
CourseItemViewController

### PR DESCRIPTION
**Pull request by caterinamandel98**
Fixes #730

### CODE REVIEW

File: iOS/ViewControllers/Courses/CourseItemViewController.swift [hunk 1]
```diff
@@ -137,3 +142,11 @@ extension CourseItemViewController: UIPageViewControllerDelegate {
     }
 
 }
+
+extension Sequence {
```
Comment (mathebox) [inline iOS/ViewControllers/Courses/CourseItemViewController.swift]: Please move this to a separate file :)

File: iOS/ViewControllers/Courses/CourseItemViewController.swift [hunk 2]
```diff
@@ -29,8 +29,13 @@ class CourseItemViewController: UIPageViewController {
...
 
             if let item = self.currentItem, let section = item.section {
-                self.progressLabel.text = "\(item.position) / \(section.items.count)"
+                let sortedCourseItems = section.items.sorted(by: \.position)
+                if let index = sortedCourseItems.firstIndex(of: item) {
+                let position = index + 1
+
+                self.progressLabel.text = "\(position) / \(section.items.count)"
                 self.progressLabel.sizeToFit()
+                }
```
Comment (mathebox) [inline iOS/ViewControllers/Courses/CourseItemViewController.swift]: We should also handle the case if the item can't be found in the `sortedCourseItems`. I would prefer something like this: `- / 14`.
