### PR TITLE
Fix displaying user data in settings tab.

### LINKED ISSUE #371: Check displaying user name and email address after SSO
**Affected Component:**
SettingsViewController

**Expected Behavior:**
- should show user's name and mail address

**Actual Behavior:**
- does show empty string

### PR DESCRIPTION
**Pull request by mathebox**
- Add animations.

Fixes #371

### CODE REVIEW

File: xikolo-common/Data/Helper/UserHelper.swift [hunk 1]
```diff
@@ -25,17 +25,21 @@ class UserHelper {
...
-    static func getByID(_ id: String) throws -> User? {
+    static func getUser(byId id: String) -> User? {
         let request: NSFetchRequest<User> = User.fetchRequest()
         request.predicate = NSPredicate(format: "id == %@", id)
         request.fetchLimit = 1
-        let users = try CoreDataHelper.executeFetchRequest(request)
-        return users.first
+        do {
+            let users = try CoreDataHelper.executeFetchRequest(request)
+            return users.first
```
Comment (bjrne) [inline xikolo-common/Data/Helper/UserHelper.swift]: Wouldn't some question marks be enough here? It's not that nice, but I think you can read the logic faster.

Comment (mathebox) [reply xikolo-common/Data/Helper/UserHelper.swift]: do you mean something like this? 
```swift
return CoreDataHelper.executeFetchRequest(request).first
```

Comment (bjrne) [reply xikolo-common/Data/Helper/UserHelper.swift]: Kind of, it that works. I though of
```swift
return (try? CoreDataHelper.executeFetchRequest(request))?.first
```
Or without the parenthesis if possible
