### PR TITLE
Trim whitespaces in URLs

### LINKED ISSUE #644: Trim whitespace from URLs on sync
**Describe the bug**
If there is some leading or trailing whitespace in an URL string supplied by the API (yes can happen), Swift fails to convert it to an `URL`.

Example:
```swift
// success
let correctURL = URL(string: "https://domain.com/path/file")

// failure
let failingURL = URL(string: "https://domain.com/path/file ")  // nil
```

**Expected behavior**
The URL should be extracted regardless of the whitespace.

**Affected Component**
Pullable resources (Video, VideoStream, ...)

**Additional context**
Possible solution:
```swift
let urlString = "https://domain.com/path/file "
let url = URL(string: urlString.trimmingCharacters(in: .whitespacesAndNewlines))
```

### PR DESCRIPTION
**Pull request by caterinamandel98**
Fixes #644 

Doesn't compile with XCode 10, still in the process of installing Xcode 11.

### CODE REVIEW

File: Common/Data/Model/Announcement.swift [hunk 1]
```diff
@@ -35,9 +35,11 @@ extension Announcement: JSONAPIPullable {
         let attributes = try object.value(for: "attributes") as JSON
         self.title = try attributes.value(for: "title")
         self.text = try attributes.value(for: "text")
-        self.imageURL = try attributes.value(for: "image_url")
         self.publishedAt = try attributes.value(for: "published_at")
         self.visited = try attributes.value(for: "visited") || self.visited // announcements can't be set to 'not visited'
+
```
Comment (CodeQualityBot) [inline Common/Data/Model/Announcement.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/openHPI/xikolo-ios/blob/6ed31ae8658b2a66ca76d19005560b4d01502273/Common/Data/Model/Announcement.swift#L40"></span>Lines should not have trailing whitespace.<br />
<code>trailing_whitespace</code> <code>Announcement.swift:40</code></td>
    </tr>
  </tbody>
</table>

File: Common/Data/Model/Course.swift [hunk 2]
```diff
@@ -106,6 +105,9 @@ extension Course: JSONAPIPullable {
         self.enrollable = try attributes.value(for: "enrollable")
         self.external = try attributes.value(for: "external")
         self.teaserStream = try attributes.value(for: "teaser_stream") ?? self.teaserStream
+
```
Comment (CodeQualityBot) [inline Common/Data/Model/Course.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/openHPI/xikolo-ios/blob/6ed31ae8658b2a66ca76d19005560b4d01502273/Common/Data/Model/Course.swift#L108"></span>Lines should not have trailing whitespace.<br />
<code>trailing_whitespace</code> <code>Course.swift:108</code></td>
    </tr>
  </tbody>
</table>

File: Common/Data/Model/DocumentLocalization.swift [hunk 3]
```diff
@@ -36,8 +36,10 @@ extension DocumentLocalization: JSONAPIPullable {
         self.title = try attributes.value(for: "title")
         self.localizationDescription = try attributes.value(for: "description")
         self.languageCode = try attributes.value(for: "language")
-        self.fileURL = try attributes.value(for: "file_url")
         self.revision = try attributes.value(for: "revision")
+
```
Comment (CodeQualityBot) [inline Common/Data/Model/DocumentLocalization.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/openHPI/xikolo-ios/blob/6ed31ae8658b2a66ca76d19005560b4d01502273/Common/Data/Model/DocumentLocalization.swift#L40"></span>Lines should not have trailing whitespace.<br />
<code>trailing_whitespace</code> <code>DocumentLocalization.swift:40</code></td>
    </tr>
  </tbody>
</table>

File: Common/Data/Model/LTIExercise.swift [hunk 4]
```diff
@@ -32,7 +32,9 @@ extension LTIExercise: JSONAPIPullable {
         self.instructions = try attributes.value(for: "instructions")
         self.weight = try attributes.value(for: "weight")
         self.allowedAttempts = try attributes.value(for: "allowed_attempts")
-        self.launchURL = try attributes.value(for: "launch_url")
+
```
Comment (CodeQualityBot) [inline Common/Data/Model/LTIExercise.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/openHPI/xikolo-ios/blob/6ed31ae8658b2a66ca76d19005560b4d01502273/Common/Data/Model/LTIExercise.swift#L35"></span>Lines should not have trailing whitespace.<br />
<code>trailing_whitespace</code> <code>LTIExercise.swift:35</code></td>
    </tr>
  </tbody>
</table>

File: Common/Data/Model/User.swift [hunk 5]
```diff
@@ -28,7 +28,9 @@ extension User: JSONAPIPullable {
     public func update(from object: ResourceData, with context: SynchronizationContext) throws {
         let attributes = try object.value(for: "attributes") as JSON
         self.name = try attributes.value(for: "name")
-        self.avatarURL = try attributes.value(for: "avatar_url")
+
```
Comment (CodeQualityBot) [inline Common/Data/Model/User.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/openHPI/xikolo-ios/blob/6ed31ae8658b2a66ca76d19005560b4d01502273/Common/Data/Model/User.swift#L31"></span>Lines should not have trailing whitespace.<br />
<code>trailing_whitespace</code> <code>User.swift:31</code></td>
    </tr>
  </tbody>
</table>

File: Common/Data/Model/Video.swift [hunk 6]
```diff
@@ -59,17 +59,25 @@ extension Video: JSONAPIPullable {
...
         self.lecturerStream = try attributes.value(for: "lecturer_stream")
         self.singleStream = try attributes.value(for: "single_stream")
         self.slidesSize = try attributes.value(for: "slides_size")
         self.slidesStream = try attributes.value(for: "slides_stream")
-        self.slidesURL = try attributes.value(for: "slides_url")
         self.summary = try attributes.value(for: "summary")
-        self.thumbnailURL = try attributes.value(for: "thumbnail_url")
-        self.transcriptURL = try attributes.value(for: "transcript_url")
         self.transcriptSize = try attributes.value(for: "transcript_size")
+
```
Comment (CodeQualityBot) [inline Common/Data/Model/Video.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/openHPI/xikolo-ios/blob/6ed31ae8658b2a66ca76d19005560b4d01502273/Common/Data/Model/Video.swift#L69"></span>Lines should not have trailing whitespace.<br />
<code>trailing_whitespace</code> <code>Video.swift:69</code></td>
    </tr>
  </tbody>
</table>

File: Common/Data/Model/Video.swift [hunk 7]
```diff
@@ -59,17 +59,25 @@ extension Video: JSONAPIPullable {
...
         self.slidesStream = try attributes.value(for: "slides_stream")
-        self.slidesURL = try attributes.value(for: "slides_url")
         self.summary = try attributes.value(for: "summary")
-        self.thumbnailURL = try attributes.value(for: "thumbnail_url")
-        self.transcriptURL = try attributes.value(for: "transcript_url")
         self.transcriptSize = try attributes.value(for: "transcript_size")
+        
+        let audioURLString = try attributes.value(for: "audio_url") as String
+        self.audioURL = URL(string: audioURLString.trimmingCharacters(in: .whitespacesAndNewlines))
+
```
Comment (CodeQualityBot) [inline Common/Data/Model/Video.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/openHPI/xikolo-ios/blob/6ed31ae8658b2a66ca76d19005560b4d01502273/Common/Data/Model/Video.swift#L72"></span>Lines should not have trailing whitespace.<br />
<code>trailing_whitespace</code> <code>Video.swift:72</code></td>
    </tr>
  </tbody>
</table>

File: Common/Data/Model/Video.swift [hunk 8]
```diff
@@ -59,17 +59,25 @@ extension Video: JSONAPIPullable {
...
-        self.thumbnailURL = try attributes.value(for: "thumbnail_url")
-        self.transcriptURL = try attributes.value(for: "transcript_url")
         self.transcriptSize = try attributes.value(for: "transcript_size")
+        
+        let audioURLString = try attributes.value(for: "audio_url") as String
+        self.audioURL = URL(string: audioURLString.trimmingCharacters(in: .whitespacesAndNewlines))
+        
+        let slidesURLString = try attributes.value(for: "slides_url") as String
+        self.slidesURL = URL(string: slidesURLString.trimmingCharacters(in: .whitespacesAndNewlines))
+
```
Comment (CodeQualityBot) [inline Common/Data/Model/Video.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/openHPI/xikolo-ios/blob/6ed31ae8658b2a66ca76d19005560b4d01502273/Common/Data/Model/Video.swift#L75"></span>Lines should not have trailing whitespace.<br />
<code>trailing_whitespace</code> <code>Video.swift:75</code></td>
    </tr>
  </tbody>
</table>

File: Common/Data/Model/Video.swift [hunk 9]
```diff
@@ -59,17 +59,25 @@ extension Video: JSONAPIPullable {
...
+        
+        let audioURLString = try attributes.value(for: "audio_url") as String
+        self.audioURL = URL(string: audioURLString.trimmingCharacters(in: .whitespacesAndNewlines))
+        
+        let slidesURLString = try attributes.value(for: "slides_url") as String
+        self.slidesURL = URL(string: slidesURLString.trimmingCharacters(in: .whitespacesAndNewlines))
+        
+        let thumbnailURLString = try attributes.value(for: "thumbnail_url") as String
+        self.thumbnailURL = URL(string: thumbnailURLString.trimmingCharacters(in: .whitespacesAndNewlines))
+
```
Comment (CodeQualityBot) [inline Common/Data/Model/Video.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/openHPI/xikolo-ios/blob/6ed31ae8658b2a66ca76d19005560b4d01502273/Common/Data/Model/Video.swift#L78"></span>Lines should not have trailing whitespace.<br />
<code>trailing_whitespace</code> <code>Video.swift:78</code></td>
    </tr>
  </tbody>
</table>

File: Common/Data/Model/EnrollmentCertificates.swift [hunk 10]
```diff
@@ -13,9 +13,14 @@ public final class EnrollmentCertificates: NSObject, NSCoding, IncludedPullable
     public var qualifiedCertificate: URL?
 
     public required init(object: ResourceData) throws {
-        self.confirmationOfParticipation = try object.value(for: "confirmation_of_participation")
-        self.recordOfAchievement = try object.value(for: "record_of_achievement")
-        self.qualifiedCertificate = try object.value(for: "qualified_certificate")
+        let recordOfAchievementURLString = try attributes.value(for: "recordOfAchievement_url") as String
+        self.recordOfAchievement = URL(string: recordOfAchievementURLString.trimmingCharacters(in: .whitespacesAndNewlines))
+
```
Comment (CodeQualityBot) [inline Common/Data/Model/EnrollmentCertificates.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/openHPI/xikolo-ios/blob/9d1487fb6408fdb62c3d55bada349d773b25315e/Common/Data/Model/EnrollmentCertificates.swift#L18"></span>Lines should not have trailing whitespace.<br />
<code>trailing_whitespace</code> <code>EnrollmentCertificates.swift:18</code></td>
    </tr>
  </tbody>
</table>

File: Common/Data/Model/EnrollmentCertificates.swift [hunk 11]
```diff
@@ -13,9 +13,14 @@ public final class EnrollmentCertificates: NSObject, NSCoding, IncludedPullable
...
     public required init(object: ResourceData) throws {
-        self.confirmationOfParticipation = try object.value(for: "confirmation_of_participation")
-        self.recordOfAchievement = try object.value(for: "record_of_achievement")
-        self.qualifiedCertificate = try object.value(for: "qualified_certificate")
+        let recordOfAchievementURLString = try attributes.value(for: "recordOfAchievement_url") as String
+        self.recordOfAchievement = URL(string: recordOfAchievementURLString.trimmingCharacters(in: .whitespacesAndNewlines))
+        
+        let confirmationOfParticipationURLString = try attributes.value(for: "confirmationOfParticipation_url") as String
+        self.confirmationOfParticipation = URL(string: confirmationOfParticipationURLString.trimmingCharacters(in: .whitespacesAndNewlines))
+
```
Comment (CodeQualityBot) [inline Common/Data/Model/EnrollmentCertificates.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/openHPI/xikolo-ios/blob/9d1487fb6408fdb62c3d55bada349d773b25315e/Common/Data/Model/EnrollmentCertificates.swift#L21"></span>Lines should not have trailing whitespace.<br />
<code>trailing_whitespace</code> <code>EnrollmentCertificates.swift:21</code></td>
    </tr>
  </tbody>
</table>

File: Common/Data/Model/VideoStream.swift [hunk 12]
```diff
@@ -16,12 +16,20 @@ public final class VideoStream: NSObject, NSCoding, IncludedPullable {
     public var thumbnailURL: URL?
 
     public required init(object: ResourceData) throws {
-        self.hdURL = try object.value(for: "hd_url")
-        self.sdURL = try object.value(for: "sd_url")
-        self.hlsURL = try object.value(for: "hls_url")
         self.hdSize = try object.value(for: "hd_size")
         self.sdSize = try object.value(for: "sd_size")
-        self.thumbnailURL = try object.value(for: "thumbnail_url")
+
```
Comment (CodeQualityBot) [inline Common/Data/Model/VideoStream.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/openHPI/xikolo-ios/blob/9d1487fb6408fdb62c3d55bada349d773b25315e/Common/Data/Model/VideoStream.swift#L21"></span>Lines should not have trailing whitespace.<br />
<code>trailing_whitespace</code> <code>VideoStream.swift:21</code></td>
    </tr>
  </tbody>
</table>

File: Common/Data/Model/VideoStream.swift [hunk 13]
```diff
@@ -16,12 +16,20 @@ public final class VideoStream: NSObject, NSCoding, IncludedPullable {
...
-        self.hdURL = try object.value(for: "hd_url")
-        self.sdURL = try object.value(for: "sd_url")
-        self.hlsURL = try object.value(for: "hls_url")
         self.hdSize = try object.value(for: "hd_size")
         self.sdSize = try object.value(for: "sd_size")
-        self.thumbnailURL = try object.value(for: "thumbnail_url")
+        
+        let hdURLString = try attributes.value(for: "hd_url") as String
+        self.hdURL = URL(string: hdURLString.trimmingCharacters(in: .whitespacesAndNewlines))
+
```
Comment (CodeQualityBot) [inline Common/Data/Model/VideoStream.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/openHPI/xikolo-ios/blob/9d1487fb6408fdb62c3d55bada349d773b25315e/Common/Data/Model/VideoStream.swift#L24"></span>Lines should not have trailing whitespace.<br />
<code>trailing_whitespace</code> <code>VideoStream.swift:24</code></td>
    </tr>
  </tbody>
</table>

File: Common/Data/Model/VideoStream.swift [hunk 14]
```diff
@@ -16,12 +16,20 @@ public final class VideoStream: NSObject, NSCoding, IncludedPullable {
...
         self.hdSize = try object.value(for: "hd_size")
         self.sdSize = try object.value(for: "sd_size")
-        self.thumbnailURL = try object.value(for: "thumbnail_url")
+        
+        let hdURLString = try attributes.value(for: "hd_url") as String
+        self.hdURL = URL(string: hdURLString.trimmingCharacters(in: .whitespacesAndNewlines))
+        
+        let sdURLString = try attributes.value(for: "sd_url") as String
+        self.sdURL = URL(string: sdURLString.trimmingCharacters(in: .whitespacesAndNewlines))
+
```
Comment (CodeQualityBot) [inline Common/Data/Model/VideoStream.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/openHPI/xikolo-ios/blob/9d1487fb6408fdb62c3d55bada349d773b25315e/Common/Data/Model/VideoStream.swift#L27"></span>Lines should not have trailing whitespace.<br />
<code>trailing_whitespace</code> <code>VideoStream.swift:27</code></td>
    </tr>
  </tbody>
</table>

File: Common/Data/Model/VideoStream.swift [hunk 15]
```diff
@@ -16,12 +16,20 @@ public final class VideoStream: NSObject, NSCoding, IncludedPullable {
...
+        
+        let hdURLString = try attributes.value(for: "hd_url") as String
+        self.hdURL = URL(string: hdURLString.trimmingCharacters(in: .whitespacesAndNewlines))
+        
+        let sdURLString = try attributes.value(for: "sd_url") as String
+        self.sdURL = URL(string: sdURLString.trimmingCharacters(in: .whitespacesAndNewlines))
+        
+        let hlsURLString = try attributes.value(for: "hls_url") as String
+        self.hlsURL = URL(string: hlsURLString.trimmingCharacters(in: .whitespacesAndNewlines))
+
```
Comment (CodeQualityBot) [inline Common/Data/Model/VideoStream.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/openHPI/xikolo-ios/blob/9d1487fb6408fdb62c3d55bada349d773b25315e/Common/Data/Model/VideoStream.swift#L30"></span>Lines should not have trailing whitespace.<br />
<code>trailing_whitespace</code> <code>VideoStream.swift:30</code></td>
    </tr>
  </tbody>
</table>

**Comment by mathebox** [comment]
Congrats on your first merged pull request @caterinamandel98 🎉
