### PR TITLE
Fix quiz submission via webview.

### LINKED ISSUE #335: Quiz submissions fail
When submitting a quiz in a webview, an error (404) will occur.

### PR DESCRIPTION
**Pull request by mathebox**
Fixes #335

### CODE REVIEW

File: xikolo-ios/ViewControllers/Courses/WebViewController.swift [hunk 1]
```diff
@@ -50,11 +50,12 @@ extension WebViewController : UIWebViewDelegate {
         let userIsLoggedIn = UserProfileHelper.isLoggedIn()
         let headerIsPresent = request.allHTTPHeaderFields?.keys.contains(Routes.HTTP_AUTH_HEADER) ?? false
 
-        if let url = request.url?.absoluteString, userIsLoggedIn && !headerIsPresent {
+        if userIsLoggedIn && !headerIsPresent {
             DispatchQueue.global().async {
                 DispatchQueue.main.async {
-                    let newRequest = NetworkHelper.getRequestForURL(url)
```
Comment (jprberlin) [inline xikolo-ios/ViewControllers/Courses/WebViewController.swift]: check if this method is obsolete now and can be removed

Comment (mathebox) [reply xikolo-ios/ViewControllers/Courses/WebViewController.swift]: No, it is still used in `WebViewController`.
